# Connects the Deployment to the Knative Broker by injecting the K_SINK env var.
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: svc-intake-binding
spec:
  # The "subject" is the workload to inject K_SINK into.
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-intake

  # The "sink" is the destination where events should be sent.
  # This assumes a Broker named 'default' in the same namespace.
  # If your broker has a different name, change it here.
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
