apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: runtime-services
build:
  platforms: [ "linux/amd64" ]

  local:
    useBuildkit: false

  artifacts:

    - image: svc-intake
      docker:
        dockerfile: Dockerfile
        target: svc-intake

    - image: svc-structure-processor
      docker:
        dockerfile: Dockerfile
        target: svc-structure-processor

    - image: svc-guardian-processor
      docker:
        dockerfile: Dockerfile
        target: svc-guardian-processor

    - image: svc-customer-lookup
      docker:
        dockerfile: Dockerfile
        target: svc-customer-lookup

    - image: svc-router
      docker:
        dockerfile: Dockerfile
        target: svc-router

    - image: ui-observer
      docker:
        dockerfile: Dockerfile
        target: ui-observer

    - image: db-customer
      docker:
        dockerfile: Dockerfile
        target: db-customer

manifests:
  rawYaml:
    - config/100-namespace.yaml
    - config/200-kafka-broker.yaml

    - db_customer/config/400-secret.yaml
    - db_customer/config/500-deployment.yaml
    - db_customer/config/600-service.yaml

    - svc_intake/config/000-deployment.yaml
    - svc_intake/config/100-service.yaml
    - svc_intake/config/200-sinkbinding.yaml

    - svc_structure_processor/config/000-deployment.yaml
    - svc_structure_processor/config/100-service.yaml
    - svc_structure_processor/config/200-trigger.yaml
    - svc_structure_processor/config/300-configmap.yaml
    - svc_structure_processor/config/310-llm-api-key-secret.yaml

    - svc_guardian_processor/config/000-deployment.yaml
    - svc_guardian_processor/config/100-service.yaml
    - svc_guardian_processor/config/200-trigger.yaml
    - svc_guardian_processor/config/300-sinkbinding.yaml
    - svc_guardian_processor/config/400-configmap.yaml
    - svc_guardian_processor/config/410-llm-api-key-secret.yaml

    - svc_customer_lookup/config/000-deployment.yaml
    - svc_customer_lookup/config/100-service.yaml
    - svc_customer_lookup/config/200-trigger.yaml
    - svc_customer_lookup/config/300-sinkbinding.yaml

    - svc_router/config/000-deployment.yaml
    - svc_router/config/100-service.yaml
    - svc_router/config/200-trigger.yaml
    - svc_router/config/300-sinkbinding.yaml
    - svc_router/config/400-configmap.yaml
    - svc_router/config/410-llm-api-key-secret.yaml

    - ui_observer/config/000-deployment.yaml
    - ui_observer/config/100-service.yaml
    - ui_observer/config/200-trigger.yaml

deploy:
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
