apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: keventmesh
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
