apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: keventmesh
spec:
  brokerClass: KafkaBroker
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
