apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-finance-responder
  namespace: keventmesh
spec:
  template:
    metadata:
      labels:
        app: svc-finance-responder
    spec:
      containers:
        - name: user-container
          image: svc-finance-responder:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
