apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-router
  namespace: keventmesh
spec:
  template:
    metadata:
      labels:
        app: svc-router
    spec:
      containers:
        - name: user-container
          image: svc-router:latest
          env:
            - name: PORT
              value: "8080"
            - name: LLM_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: svc-router
                  key: apiBaseUrl
            - name: LLM_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: svc-router
                  key: modelName
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-router-llm-secret
                  key: apiKey
          ports:
            - containerPort: 8080
              name: http1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
