apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-customer-lookup
  namespace: keventmesh
spec:
  template:
    metadata:
      labels:
        app: svc-customer-lookup
    spec:
      containers:
        - name: user-container
          image: svc-customer-lookup:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-customer-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-customer-secret
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-customer-secret
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-customer-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-customer-secret
                  key: password
          ports:
            - containerPort: 8080
              name: http1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
