apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-guardian-processor
  namespace: keventmesh
spec:
  template:
    metadata:
      labels:
        app: svc-guardian-processor
    spec:
      containers:
        - name: user-container
          image: svc-guardian-processor:latest
          env:
            - name: LLM_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: svc-guardian-processor
                  key: apiBaseUrl
            - name: LLM_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: svc-guardian-processor
                  key: modelName
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-guardian-processor-llm-secret
                  key: apiKey
          ports:
            - containerPort: 8080
              name: http1
